### ISSUE TITLE
Bad Request on /api/schoolYear [Reproduce]

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#169]
try to reproduce

https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/44/

```
Stacktrace (most recent call first):

  at captureMessage (/vendor.40f7b1c157ed9f957d1b.bundle.js:1438:18927)
  at captureException (/vendor.40f7b1c157ed9f957d1b.bundle.js:1438:18520)
  at r (/vendor.40f7b1c157ed9f957d1b.bundle.js:1438:17994)
  at [569]/</</E</E</t.prototype.invokeTask (/polyfills.7c7ad1c746a1248bf10c.bundle.js:37:9659)
  at onInvokeTask (/vendor.40f7b1c157ed9f957d1b.bundle.js:93:2557)
  at [569]/</</E</E</t.prototype.invokeTask (/polyfills.7c7ad1c746a1248bf10c.bundle.js:37:9572)
  at [569]/</</E</x</e.prototype.runTask (/polyfills.7c7ad1c746a1248bf10c.bundle.js:37:5351)
  at t/this.invoke (/polyfills.7c7ad1c746a1248bf10c.bundle.js:37:10539)
  at EventListener.handleEvent*invokeAddFunc (/polyfills.7c7ad1c746a1248bf10c.bundle.js:37:16350)
  at c (/polyfills.7c7ad1c746a1248bf10c.bundle.js:9:1619)
...
(40 additional frame(s) were not displayed)

Response with status: 400 Bad Request for URL: https://outcobra-a.pegnu.cloud/backend/api/schoolYear
```

**Comment by jmesserli** [comment]
I think this is related to https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/38/

**Comment by needToRoll** [comment]
The referenced sentry issue only appears if our database does not contain the auth0 id of users already registred in our application.

This should not be an issue in production but it is still kind of ugly. What do you guys think we can and should do about it? @jmesserli @M4R1KU

**Comment by M4R1KU** [comment]
I already mentioned that multiple times but now you have it black on white if you look at #150
