### ISSUE TITLE
TypeError: this.taskService is undefined

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#182]
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/51/

```
TypeError: this.taskService is undefined
  at 9w/n/p</t.prototype.updateProgress (/main.183f6c31b4253f5751fb.bundle.js:8:5138)
  at XO5T/u</e.prototype._tryNext (/vendor.b63e0336aaa5b04105a7.bundle.js:782:12771)
  at XO5T/u</e.prototype._next (/vendor.b63e0336aaa5b04105a7.bundle.js:782:12673)
  at mmVS/u</e.prototype.next (/vendor.b63e0336aaa5b04105a7.bundle.js:1104:5602)
  at 8hgl/c</e.prototype._next (/vendor.b63e0336aaa5b04105a7.bundle.js:232:3897)
...
(15 additional frame(s) were not displayed)
```

**Comment by jmesserli** [comment]
This happens when the progress of a task is updated.
