### ISSUE TITLE
Error: Uncaught (in promise): Error: No provider for t!

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#229]
The last pull request broke production apparently

https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/94/

```
Error: Uncaught (in promise): Error: No provider for t!
g@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:2484
k@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:205:287
L@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:205:546
3j3K/</ao</t.prototype._throwOrNull@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:352:9224
3j3K/</ao</t.prototype._getByKeyDefault@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:352:9552
3j3K/</ao</t.prototype._getByKey@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:352:8937
3j3K/</ao</t.prototype.get@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:352:7345
get@https://outcobra-a.pegnu.cloud/main.7a26c51640b4eac5ad3a.bundle.js:19:13850
get@https://outcobra-a.pegnu.cloud/main.7a26c51640b4eac5ad3a.bundle.js:19:14026
kke6/Fe</t.prototype.getInternal@https://outcobra-a.pegnu.cloud/main.7a26c51640b4eac5ad3a.bundle.js:19:24709
3j3K/</Io</t.prototype.get@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:3686
un@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:282:5576
sn@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:282:4479
tn@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:282:2784
Hn@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:310:3974
In@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:310:2855
rr@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:310:8326
3j3K/</pa</e.prototype.create@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:387:20557
3j3K/</Eo</e.prototype.create@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:2632
3j3K/</es</e.prototype.bootstrap@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:15633
3j3K/</$o</e.prototype._moduleDoBootstrap/<@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:13234
3j3K/</$o</e.prototype._moduleDoBootstrap@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:13186
3j3K/</$o</e.prototype._bootstrapModuleFactoryWithZone/</</<@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:12697
ZSR1/</</E</E</t.prototype.invoke@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:9881
onInvoke@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:8109
ZSR1/</</E</E</t.prototype.invoke@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:9808
ZSR1/</</E</_</n.prototype.run@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:5076
p/<@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:2126
ZSR1/</</E</E</t.prototype.invokeTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:10556
onInvokeTask@https://outcobra-a.pegnu.cloud/vendor.061eaf196603f85bc805.bundle.js:366:8009
ZSR1/</</E</E</t.prototype.invokeTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:10469
ZSR1/</</E</_</n.prototype.runTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:5725
u@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:660
t/this.invoke@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:11564
EventListener.handleEvent*invokeAddFunc@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:16608
c@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:9:1631
ZSR1/</</E</E</t.prototype.scheduleTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:10306
onScheduleTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:7475
ZSR1/</</E</E</t.prototype.scheduleTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37:10185
ZSR1/</</E</_</n.prototype.scheduleTask@https://outcobra-a.pegnu.cloud/polyfills.6840863a1228436cb41f.bundle.js:37...
  at appInits (./src/app/core/services/factories.ts:16:17)
  at this (./src/$_gendir/app/app.module.ngfactory.ts:582:37)
  at modules (./src/main.ts:10)
...
(45 additional frame(s) were not displayed)
```

**Comment by jmesserli** [comment]
Restored production by reverting to the last frontend docker image
