### ISSUE TITLE
Error: Unable to process animations due to the following failed trigger transitions

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#349]
https://sentry.pegnu.cloud/pg/oc/issues/286/

```
Error: Unable to process animations due to the following failed trigger transitions
 @topLevelRouteAnimation has failed due to:

- `query(":enter")` returned zero elements. (Use `query(":enter", { optional: true })` if you wish to allow this.)

  at t.reportError (/opt/jenkins-agent/home/workspace/a_outstanding-cobra_develop-TUXIQBGU7UA2AMUPAQTZUR4LTIJPK2NAHDMXYCTBYLDYM2YPQ2CA@2/frontend/node_modules/@angular/animations/esm5/browser.js.pre-build-optimizer.js:4502:14)
  at reportError (/opt/jenkins-agent/home/workspace/a_outstanding-cobra_develop-TUXIQBGU7UA2AMUPAQTZUR4LTIJPK2NAHDMXYCTBYLDYM2YPQ2CA@2/frontend/node_modules/@angular/animations/esm5/browser.js.pre-build-optimizer.js:4643:17)
  at _flushAnimations (/opt/jenkins-agent/home/workspace/a_outstanding-cobra_develop-TUXIQBGU7UA2AMUPAQTZUR4LTIJPK2NAHDMXYCTBYLDYM2YPQ2CA@2/frontend/node_modules/@angular/animations/esm5/browser.js.pre-build-optimizer.js:4460:31)
  at flush (/opt/jenkins-agent/home/workspace/a_outstanding-cobra_develop-TUXIQBGU7UA2AMUPAQTZUR4LTIJPK2NAHDMXYCTBYLDYM2YPQ2CA@2/frontend/node_modules/@angular/animations/esm5/browser.js.pre-build-optimizer.js:5700:31)
  at flush (/opt/jenkins-agent/home/workspace/a_outstanding-cobra_develop-TUXIQBGU7UA2AMUPAQTZUR4LTIJPK2NAHDMXYCTBYLDYM2YPQ2CA@2/frontend/node_modules/@angular/platform-browser/esm5/animations.js.pre-build-optimizer.js:370:29)
...
(43 additional frame(s) were not displayed)
```

**Comment by jmesserli** [comment]
Happens right after you log in sometimes. Normally on first page load.
